-- Positions des partis politiques de Lévis
-- Extraction depuis POSITIONS-PARTIS-LEVIS.md
-- 3 partis × 21 questions = 63 positions

INSERT INTO public.party_positions (party_id, question_id, position, source, note) VALUES

-- Lévis Force 10 (21 positions)
('levis-force-10', 'lev_q1_troisieme_lien', 'PA', 'Déclarations publiques', 'Continuité avec position Lehouillier favorable au 3e lien'),
('levis-force-10', 'lev_q2_pistes_cyclables', 'PA', 'Réalisations publiques', 'Réalisations mobilité durable et transport actif documentées'),
('levis-force-10', 'lev_q3_traverse_quebec_levis', 'PA', 'Programme politique', 'Amélioration services transport collectif cohérente avec réalisations'),
('levis-force-10', 'lev_q4_priorite_mobilite_active', 'N', 'Analyse politique', 'Position modérée entre développement urbain et mobilité active'),
('levis-force-10', 'lev_q5_quotas_logements_abordables', 'N', 'Programme politique', 'Aucune position explicite sur quotas dans programme'),
('levis-force-10', 'lev_q6_reduction_depenses_taxes', 'FA', 'Engagement électoral', 'Engagement central: hausse taxes limitée maximum à l''inflation'),
('levis-force-10', 'lev_q7_immeubles_grande_hauteur', 'N', 'Analyse politique', 'Approche pragmatique développement sans position radicale'),
('levis-force-10', 'lev_q8_interdire_essence_centre_ville', 'PD', 'Tendance politique', 'Résistance aux mesures environnementales radicales'),
('levis-force-10', 'lev_q9_protection_espaces_verts', 'PA', 'Réalisations publiques', 'Réalisations environnementales et qualité de vie prioritaires'),
('levis-force-10', 'lev_q10_transition_carboneutre', 'N', 'Analyse politique', 'Transition écologique sans engagement radical'),
('levis-force-10', 'lev_q11_reduction_dechets', 'N', 'Tendance politique', 'Maintien qualité services sans réduction drastique'),
('levis-force-10', 'lev_q12_augmentation_taxes', 'PD', 'Engagement électoral', 'Opposition hausses taxes au-delà inflation'),
('levis-force-10', 'lev_q13_pouvoir_conseils_quartier', 'N', 'Analyse politique', 'Continuité structure gouvernance existante'),
('levis-force-10', 'lev_q14_reduction_dette', 'PA', 'Programme politique', 'Priorité services essentiels dans gestion rigoureuse'),
('levis-force-10', 'lev_q15_avantages_fiscaux_entreprises', 'PA', 'Réalisations publiques', 'Réalisations croissance économique documentées'),
('levis-force-10', 'lev_q16_limitation_touristes', 'N', 'Analyse politique', 'Position modérée développement vs qualité vie'),
('levis-force-10', 'lev_q17_soutien_organismes_communautaires', 'N', 'Analyse politique', 'Soutien sans engagement spécifique augmentation'),
('levis-force-10', 'lev_q18_augmentation_effectifs_policiers', 'N', 'Analyse politique', 'Approche pragmatique selon besoins locaux'),
('levis-force-10', 'lev_q19_investissement_infrastructures_loisirs_sportives', 'PA', 'Réalisations publiques', 'Réalisations qualité de vie et services proximité'),
('levis-force-10', 'lev_q20_protection_patrimoine', 'PA', 'Programme politique', 'Protection patrimoine avec développement responsable'),
('levis-force-10', 'lev_q21_enjeux_prioritaires', 'FA', 'Orientations politiques du parti', 'Priorités: Gestion des finances municipales, Transport et mobilité, Services municipaux'),

-- Repensons Lévis (21 positions)
('repensons-levis', 'lev_q1_troisieme_lien', 'N', 'Analyse politique', 'Position non claire de l''opposition, approche prudente'),
('repensons-levis', 'lev_q2_pistes_cyclables', 'PA', 'Orientation politique', 'Orientation centre-gauche favorable transport actif'),
('repensons-levis', 'lev_q3_traverse_quebec_levis', 'PA', 'Cohérence politique', 'Cohérent avec vision transport durable et services'),
('repensons-levis', 'lev_q4_priorite_mobilite_active', 'PA', 'Orientation politique', 'Soutien priorité transports actifs et durables'),
('repensons-levis', 'lev_q5_quotas_logements_abordables', 'PA', 'Valeurs politiques', 'Cohérent avec réduction iniquités et justice sociale'),
('repensons-levis', 'lev_q6_reduction_depenses_taxes', 'FA', 'Engagement électoral', 'Engagement central: plafonnement taxes résidentielles à l''IPC'),
('repensons-levis', 'lev_q7_immeubles_grande_hauteur', 'N', 'Programme politique', 'Pilier développement encadré sans position extrême'),
('repensons-levis', 'lev_q8_interdire_essence_centre_ville', 'N', 'Tendance politique', 'Approche environnementale progressive sans radicalisme'),
('repensons-levis', 'lev_q9_protection_espaces_verts', 'PA', 'Mandat politique', 'Enjeux environnementaux dans mandat du parti'),
('repensons-levis', 'lev_q10_transition_carboneutre', 'PA', 'Orientation politique', 'Soutien transition écologique cohérent orientation'),
('repensons-levis', 'lev_q11_reduction_dechets', 'N', 'Analyse politique', 'Équilibre entre services municipaux et environnement'),
('repensons-levis', 'lev_q12_augmentation_taxes', 'N', 'Tendance politique', 'Acceptation sélective hausses pour projets prioritaires'),
('repensons-levis', 'lev_q13_pouvoir_conseils_quartier', 'FA', 'Priorité politique', 'Participation citoyenne et pouvoir arrondissements prioritaire'),
('repensons-levis', 'lev_q14_reduction_dette', 'PA', 'Programme politique', 'Pilier prioriser entretien infrastructures existantes'),
('repensons-levis', 'lev_q15_avantages_fiscaux_entreprises', 'PD', 'Tendance politique', 'Résistance avantages fiscaux sans contreparties sociales'),
('repensons-levis', 'lev_q16_limitation_touristes', 'N', 'Analyse politique', 'Position modérée développement vs qualité vie locale'),
('repensons-levis', 'lev_q17_soutien_organismes_communautaires', 'FA', 'Mandat politique', 'Réduction iniquités et enjeux sociaux dans mandat'),
('repensons-levis', 'lev_q18_augmentation_effectifs_policiers', 'N', 'Programme politique', 'Pilier sécurité sans focus exclusif sur policiers'),
('repensons-levis', 'lev_q19_investissement_infrastructures_loisirs_sportives', 'PA', 'Priorité politique', 'Priorité infrastructures et services de proximité'),
('repensons-levis', 'lev_q20_protection_patrimoine', 'PA', 'Cohérence politique', 'Protection patrimoine cohérente avec participation citoyenne'),
('repensons-levis', 'lev_q21_enjeux_prioritaires', 'FA', 'Orientations politiques du parti', 'Priorités: Gestion des finances municipales, Services municipaux, Développement économique et social'),

-- Prospérité Lévis (21 positions)
('prosperite-levis', 'lev_q1_troisieme_lien', 'FA', 'Position publique', 'Position très claire pour 3e lien à l''est, opposition au tracé central'),
('prosperite-levis', 'lev_q2_pistes_cyclables', 'N', 'Priorité politique', 'Focus circulation automobile, position neutre sur vélo'),
('prosperite-levis', 'lev_q3_traverse_quebec_levis', 'PA', 'Cohérence politique', 'Amélioration mobilité cohérente avec focus circulation'),
('prosperite-levis', 'lev_q4_priorite_mobilite_active', 'PD', 'Position politique', 'Opposition réduction espace automobile pour mobilité active'),
('prosperite-levis', 'lev_q5_quotas_logements_abordables', 'N', 'Programme politique', 'Développement responsable sans contraintes réglementaires'),
('prosperite-levis', 'lev_q6_reduction_depenses_taxes', 'PA', 'Valeurs politiques', 'Gestion rigoureuse et responsabilité fiscale intergénérationnelle'),
('prosperite-levis', 'lev_q7_immeubles_grande_hauteur', 'PA', 'Position politique', 'Optimisation utilisation terrains pour développement'),
('prosperite-levis', 'lev_q8_interdire_essence_centre_ville', 'FD', 'Position politique', 'Opposition ferme aux mesures environnementales radicales'),
('prosperite-levis', 'lev_q9_protection_espaces_verts', 'N', 'Analyse politique', 'Équilibre entre développement et espaces verts'),
('prosperite-levis', 'lev_q10_transition_carboneutre', 'N', 'Tendance politique', 'Transition écologique avec considération coûts'),
('prosperite-levis', 'lev_q11_reduction_dechets', 'PA', 'Priorité politique', 'Maintien et amélioration services municipaux'),
('prosperite-levis', 'lev_q12_augmentation_taxes', 'PD', 'Position politique', 'Opposition hausses taxes, priorité gestion efficace'),
('prosperite-levis', 'lev_q13_pouvoir_conseils_quartier', 'N', 'Priorité politique', 'Focus efficacité administrative sur décentralisation'),
('prosperite-levis', 'lev_q14_reduction_dette', 'FA', 'Valeurs politiques', 'Gestion rigoureuse et responsabilité fiscale intergénérationnelle'),
('prosperite-levis', 'lev_q15_avantages_fiscaux_entreprises', 'PA', 'Position politique', 'Attraction entreprises pour développement économique'),
('prosperite-levis', 'lev_q16_limitation_touristes', 'PD', 'Position politique', 'Opposition limitations développement économique/touristique'),
('prosperite-levis', 'lev_q17_soutien_organismes_communautaires', 'N', 'Analyse politique', 'Soutien ciblé sans engagement augmentation systématique'),
('prosperite-levis', 'lev_q18_augmentation_effectifs_policiers', 'PA', 'Engagement politique', 'Engagement assurer sécurité dans quartiers'),
('prosperite-levis', 'lev_q19_investissement_infrastructures_loisirs_sportives', 'FA', 'Engagement politique', 'Engagement soutien infrastructures sportives et communautaires'),
('prosperite-levis', 'lev_q20_protection_patrimoine', 'PA', 'Valeurs politiques', 'Sentiment appartenance et valorisation patrimoine'),
('prosperite-levis', 'lev_q21_enjeux_prioritaires', 'FA', 'Orientations politiques du parti', 'Priorités: Transport et mobilité, Gestion des finances municipales, Services municipaux');