-- Positions des partis politiques de Laval
-- Extraction depuis POSITIONS-PARTIS-LAVAL.md
-- 3 partis × 21 questions = 63 positions

INSERT INTO public.party_positions (party_id, question_id, position, source, note) VALUES

-- Mouvement lavallois (21 positions)
('mouvement-lavallois', 'lav_q1_srb_montreal', 'FA', 'Priorités infrastructures 2025', 'Le maire Boyer a développé plusieurs projets de transport structurant. Priorité infrastructure 2025 inclut amélioration transport'),
('mouvement-lavallois', 'lav_q2_pistes_cyclables', 'PA', 'Plan mobilité active Laval', 'Plan mobilité active existant, bien que retards reconnus. Engagement environnemental fort'),
('mouvement-lavallois', 'lav_q3_equilibre_developpement_espaces_verts', 'FA', 'Programme politique ML', 'Programme environnemental fort, protection milieux naturels. Vision 2035 priorise espaces verts'),
('mouvement-lavallois', 'lav_q4_priorite_mobilite_active', 'PA', 'Plan mobilité active', 'Engagement dans Plan mobilité active, bien que défis de mise en œuvre reconnus'),
('mouvement-lavallois', 'lav_q5_quotas_logements_abordables', 'FA', 'Le Devoir mai 2025', 'Utilisation superpouvoirs municipaux pour logement abordable. Politiques actives en cours'),
('mouvement-lavallois', 'lav_q6_reduction_depenses_taxes', 'PD', 'Priorités campagne 2025', 'Opération 440M$ infrastructures nécessite investissements. Priorité services qualité'),
('mouvement-lavallois', 'lav_q7_immeubles_grande_hauteur', 'PA', 'Politiques aménagement', 'Politiques densification avec superpouvoirs municipaux. Vision développement durable'),
('mouvement-lavallois', 'lav_q8_interdire_essence_centre_ville', 'PA', 'Programme politique ML', 'Engagement environnemental fort, transition écologique dans programme politique'),
('mouvement-lavallois', 'lav_q9_protection_espaces_verts', 'FA', 'Programme politique', 'Programme environnemental explicite, protection milieux naturels prioritaire'),
('mouvement-lavallois', 'lav_q10_transition_carboneutre', 'FA', 'Programme politique ML', 'Engagement transition écologique central dans programme politique 2023'),
('mouvement-lavallois', 'lav_q11_reduction_dechets', 'PD', 'Services municipaux qualité', 'Priorité services qualité citoyens vs réduction services pour environnement'),
('mouvement-lavallois', 'lav_q12_augmentation_taxes', 'PA', 'Investissements infrastructures', 'Opération 440M$ infrastructures nécessite investissements pour projets écoresponsables'),
('mouvement-lavallois', 'lav_q13_pouvoir_conseils_quartier', 'PA', 'Programme politique', 'Valeurs gouvernance participative et consultation citoyenne dans programme'),
('mouvement-lavallois', 'lav_q14_reduction_dette', 'PD', 'Opération 440M$', 'Priorité projets avenir et infrastructures modernes vs seulement services essentiels'),
('mouvement-lavallois', 'lav_q15_avantages_fiscaux_entreprises', 'PA', 'Valeurs développement économique', 'Développement économique durable prioritaire. Attraction entreprises pour emplois'),
('mouvement-lavallois', 'lav_q16_limitation_touristes', 'PA', 'Approche équilibrée', 'Équilibre développement touristique et qualité vie résidents dans gouvernance'),
('mouvement-lavallois', 'lav_q17_soutien_organismes_communautaires', 'FA', 'Valeurs fondamentales ML', 'Équité et justice sociale valeurs centrales. Support services sociaux essentiels'),
('mouvement-lavallois', 'lav_q18_augmentation_effectifs_policiers', 'PA', 'Programme politique', 'Sécurité population prioritaire dans réalisations et programme politique'),
('mouvement-lavallois', 'lav_q19_investissement_infrastructures_loisirs_sportives', 'FA', 'Services qualité', 'Services municipaux qualité prioritaires. Infrastructures proximité dans programme'),
('mouvement-lavallois', 'lav_q20_protection_patrimoine', 'PA', 'Programme développement durable', 'Développement durable inclut préservation patrimoine et identité locale'),
('mouvement-lavallois', 'lav_q21_enjeux_prioritaires', 'FA', 'Programme politique 2025', 'Priorités: Services municipaux, Environnement espaces verts, Transport mobilité'),

-- Parti Laval (21 positions)
('parti-laval', 'lav_q1_srb_montreal', 'PA', 'Plateforme électorale 2025', 'Plateforme axée sur mobilité fluide et accessible. Support projets structurants qui désengorgent Laval'),
('parti-laval', 'lav_q2_pistes_cyclables', 'PA', 'Plateforme mobilité', 'Support transport actif mais priorité sécurité et efficacité. Approche plus modérée'),
('parti-laval', 'lav_q3_equilibre_developpement_espaces_verts', 'PA', 'Plateforme 2025', 'Plateforme valorise durabilité et protection environnement. Mention protection milieux naturels'),
('parti-laval', 'lav_q4_priorite_mobilite_active', 'N', 'Plateforme mobilité équitable', 'Priorité équilibre entre tous modes transport. Pas de favoritisme marqué mobilité active'),
('parti-laval', 'lav_q5_quotas_logements_abordables', 'PA', 'Plateforme habitation', 'Support logement abordable dans plateforme. Approche équilibrée développement'),
('parti-laval', 'lav_q6_reduction_depenses_taxes', 'FA', 'Plateforme 2025', 'Plateforme axée protection portefeuille citoyens, limitation hausses taxes, efficacité dépenses'),
('parti-laval', 'lav_q7_immeubles_grande_hauteur', 'N', 'Plateforme aménagement urbain', 'Position équilibrée entre développement et préservation. Pas de favoritisme hauteur'),
('parti-laval', 'lav_q8_interdire_essence_centre_ville', 'PD', 'Approche pragmatique', 'Approche plus pragmatique. Priorité efficacité vs mesures radicales environnementales'),
('parti-laval', 'lav_q9_protection_espaces_verts', 'PA', 'Plateforme 2025', 'Valeurs durabilité dans plateforme. Protection environnement mentionnée'),
('parti-laval', 'lav_q10_transition_carboneutre', 'PA', 'Plateforme environnement', 'Support général environnement mais priorité coûts et efficacité'),
('parti-laval', 'lav_q11_reduction_dechets', 'PA', 'Plateforme services essentiels', 'Amélioration services essentiels prioritaire dans plateforme. Services avant projets avenir'),
('parti-laval', 'lav_q12_augmentation_taxes', 'FD', 'Plateforme finances responsables', 'Opposition centrale aux hausses taxes. Protection portefeuille citoyens prioritaire'),
('parti-laval', 'lav_q13_pouvoir_conseils_quartier', 'PA', 'Valeurs plateforme', 'Valeur transparence et proximité citoyens. Remettre citoyens au cœur décisions'),
('parti-laval', 'lav_q14_reduction_dette', 'FA', 'Plateforme services essentiels', 'Services essentiels (collecte, déneigement) prioritaires avant investir projets avenir'),
('parti-laval', 'lav_q15_avantages_fiscaux_entreprises', 'N', 'Approche équilibrée', 'Équilibre entre développement économique et protection finances municipales'),
('parti-laval', 'lav_q16_limitation_touristes', 'N', 'Pas de position claire', 'Position non clairement définie sur limitation tourisme vs développement économique'),
('parti-laval', 'lav_q17_soutien_organismes_communautaires', 'PA', 'Plateforme services citoyens', 'Support services essentiels incluant aide organismes communautaires'),
('parti-laval', 'lav_q18_augmentation_effectifs_policiers', 'FA', 'Plateforme sécurité', 'Sécurité routière et quartiers priorité explicite. Augmentation présence policière'),
('parti-laval', 'lav_q19_investissement_infrastructures_loisirs_sportives', 'FA', 'Plateforme infrastructures', 'Infrastructures proximité prioritaires. Quartiers équipés et accueillants'),
('parti-laval', 'lav_q20_protection_patrimoine', 'FA', 'Plateforme culture et patrimoine', 'Valorisation culture, patrimoine et langue prioritaire dans plateforme'),
('parti-laval', 'lav_q21_enjeux_prioritaires', 'FA', 'Plateforme 2025', 'Priorités: Gestion finances municipales, Sécurité publique, Services municipaux'),

-- Action Laval (21 positions)
('action-laval', 'lav_q1_srb_montreal', 'PA', 'LinkedIn Action Laval', 'Support au développement économique nécessite amélioration transport. Candidats parlent accessibilité'),
('action-laval', 'lav_q2_pistes_cyclables', 'N', 'Communications publiques', 'Pas de position claire trouvée sur développement pistes cyclables spécifiquement'),
('action-laval', 'lav_q3_equilibre_developpement_espaces_verts', 'N', 'Communications publiques', 'Position non clairement définie dans sources disponibles. Focus sur économie et finances'),
('action-laval', 'lav_q4_priorite_mobilite_active', 'N', 'Communications disponibles', 'Position non définie clairement sur priorisation mobilité active vs automobile'),
('action-laval', 'lav_q5_quotas_logements_abordables', 'N', 'Communications publiques', 'Pas de position claire sur quotas obligatoires trouvée dans sources'),
('action-laval', 'lav_q6_reduction_depenses_taxes', 'FA', 'Courrier Laval février 2025', 'Frédéric Mayer veut mettre ordre dans finances. Focus gestion efficace ressources'),
('action-laval', 'lav_q7_immeubles_grande_hauteur', 'N', 'Communications analysées', 'Pas de position claire sur immeubles grande hauteur dans sources disponibles'),
('action-laval', 'lav_q8_interdire_essence_centre_ville', 'PD', 'Orientation économique', 'Focus économie et praticité. Mesures radicales incompatibles avec approche économique'),
('action-laval', 'lav_q9_protection_espaces_verts', 'N', 'Communications disponibles', 'Position non définie clairement sur équilibre espaces verts vs développement'),
('action-laval', 'lav_q10_transition_carboneutre', 'PD', 'Priorités financières', 'Focus gestion financière rigide. Réticence coûts supplémentaires pour transition'),
('action-laval', 'lav_q11_reduction_dechets', 'PA', 'Priorités services municipaux', 'Focus services de base efficaces. Amélioration services vs considérations environnementales'),
('action-laval', 'lav_q12_augmentation_taxes', 'FD', 'Positions financières', 'Mayer veut ordre dans finances. Opposition augmentation taxes pour projets'),
('action-laval', 'lav_q13_pouvoir_conseils_quartier', 'PA', 'Description parti LinkedIn', 'Parti opposition prône ouverture et écoute citoyens selon description LinkedIn'),
('action-laval', 'lav_q14_reduction_dette', 'PA', 'Priorités gestion financière', 'Gestion financière rigoureuse et efficacité avant projets coûteux'),
('action-laval', 'lav_q15_avantages_fiscaux_entreprises', 'FA', 'Orientation économique parti', 'Focus dynamisme économique central. Attraction entreprises pour emplois et croissance'),
('action-laval', 'lav_q16_limitation_touristes', 'PD', 'Focus développement économique', 'Priorité développement économique inclurait tourism sans limitations restrictives'),
('action-laval', 'lav_q17_soutien_organismes_communautaires', 'N', 'Pas de position claire', 'Position non clairement définie sur financement organismes vs priorités financières'),
('action-laval', 'lav_q18_augmentation_effectifs_policiers', 'PA', 'Priorités développement', 'Sécurité publique importante pour développement économique et qualité vie'),
('action-laval', 'lav_q19_investissement_infrastructures_loisirs_sportives', 'PA', 'Focus services municipaux', 'Services municipaux de base incluent infrastructures sportives et loisirs'),
('action-laval', 'lav_q20_protection_patrimoine', 'N', 'Pas de position claire', 'Position non clairement définie sur équilibre patrimoine vs développement économique'),
('action-laval', 'lav_q21_enjeux_prioritaires', 'FA', 'Orientations parti', 'Priorités: Gestion finances municipales, Développement économique, Services municipaux');