-- Insertion des positions des partis sur les 21 questions
-- Données extraites de lib/boussole-data.ts

INSERT INTO party_positions (
  party_id,
  question_id,
  position,
  source,
  note,
  quote
) VALUES

-- Alliance citoyenne de Québec (ACQ)
('alliance_citoyenne', 'q1_tramway', 'PD', 'Déclarations publiques et articles de presse analysant la position du parti sur les grands projets d''infrastructure', 'Favorise plutôt une révision complète du projet de transport structurant avec une approche plus consensuelle', NULL),
('alliance_citoyenne', 'q2_pistes_cyclables', 'PA', 'Communications officielles du parti mentionnant la mobilité durable et le transport actif', 'Soutient le développement du réseau cyclable mais avec une approche équilibrée qui tient compte de tous les usagers', NULL),
('alliance_citoyenne', 'q3_troisieme_lien', 'FA', 'Projet spécifique de jetée de Beauport à l''Île d''Orléans puis pont vers Lévis', 'Propose un projet de 3e lien estimé entre 1 et 3 milliards de dollars, rejetant l''option tunnel', NULL),
('alliance_citoyenne', 'q4_priorite_mobilite_active', 'PA', 'Orientation générale favorable au transport collectif', 'Soutient la réduction des stationnements pour promouvoir le transport collectif', NULL),
('alliance_citoyenne', 'q5_quotas_logements_abordables', 'PA', 'Mentions de la crise du logement dans les communications', 'Soutient des mesures pour augmenter l''offre de logements abordables', NULL),
('alliance_citoyenne', 'q6_reduction_depenses_taxes', 'FD', 'Philosophie libertarienne favorisant réduction des dépenses publiques', 'Fortement en faveur de la réduction des taxes et des dépenses municipales', NULL),
('alliance_citoyenne', 'q7_immeubles_grande_hauteur', 'FD', 'Orientation développement économique et densification urbaine efficace', 'Favorise les immeubles de grande hauteur pour optimiser l''utilisation des terrains et le développement économique', NULL),
('alliance_citoyenne', 'q8_interdire_essence_centre_ville', 'FA', 'Position climato-réaliste sceptique des mesures environnementales contraignantes', 'Opposé aux interdictions jugées trop radicales et coûteuses', NULL),
('alliance_citoyenne', 'q9_protection_espaces_verts', 'PA', NULL, NULL, NULL),
('alliance_citoyenne', 'q10_transition_carboneutre', 'PD', NULL, NULL, NULL),
('alliance_citoyenne', 'q11_reduction_dechets', 'FA', 'Position climato-réaliste de Daniel Brisson remettant en question le rôle humain dans le réchauffement', 'Approche sceptique des politiques climatiques coûteuses', NULL),
('alliance_citoyenne', 'q12_augmentation_taxes', 'FD', 'Philosophie libertarienne opposée aux mesures contraignantes pour les citoyens', 'Privilégie l''autonomie citoyenne plutôt que les règlements stricts', NULL),
('alliance_citoyenne', 'q13_pouvoir_conseils_quartier', 'FA', NULL, NULL, NULL),
('alliance_citoyenne', 'q14_reduction_dette', 'PD', NULL, NULL, NULL),
('alliance_citoyenne', 'q15_avantages_fiscaux_entreprises', 'PA', NULL, NULL, NULL),
('alliance_citoyenne', 'q16_limitation_touristes', 'FD', 'Programme explicite de réduction des taxes et abolition de certaines taxes municipales', 'Veut abolir les parcomètres et la taxe d''accueil, réduire les dépenses publiques', NULL),
('alliance_citoyenne', 'q17_soutien_organismes_communautaires', 'PD', NULL, NULL, NULL),
('alliance_citoyenne', 'q18_augmentation_effectifs_policiers', 'PA', NULL, NULL, NULL),
('alliance_citoyenne', 'q19_investissement_infrastructures_loisirs_sportives', 'PA', NULL, NULL, NULL),
('alliance_citoyenne', 'q20_protection_patrimoine', 'PD', NULL, NULL, NULL),
('alliance_citoyenne', 'q21_enjeux_prioritaires', 'PA', NULL, NULL, NULL),

-- Équipe priorité Québec (EPQ)
('equipe_priorite_quebec', 'q1_tramway', 'FD', 'Approche pragmatique, opposition constructive', 'Position équilibrée - demande acceptabilité sociale et évaluations responsables des projets de transport', NULL),
('equipe_priorite_quebec', 'q2_pistes_cyclables', 'PA', 'Valeurs affichées sur le site concernant le développement durable', 'Il est primordial de combiner développement et environnement afin de faire prospérer notre ville.', NULL),
('equipe_priorite_quebec', 'q3_troisieme_lien', 'PA', 'Stevens Mélançon, 2025 - Réaction au corridor choisi par la CAQ', 'Je ne peux qu''être déçu pour les citoyens que je représente du côté est qui pensaient fort que bien que le tracé aller passer à cette place-là - Position nuancée, représente les citoyens de l''est', NULL),
('equipe_priorite_quebec', 'q4_priorite_mobilite_active', 'PA', 'Approche pragmatique favorable au transport collectif', 'Soutient les mesures encourageant le transport collectif si socialement acceptables', NULL),
('equipe_priorite_quebec', 'q5_quotas_logements_abordables', 'FA', 'Valeur d''équité mentionnée sur le site', 'Favorable à l''accès au logement mais peu de détails sur les mécanismes', NULL),
('equipe_priorite_quebec', 'q6_reduction_depenses_taxes', 'PA', 'Opposition constructive aux dépenses excessives', 'Favorise une gestion responsable des finances municipales', NULL),
('equipe_priorite_quebec', 'q7_immeubles_grande_hauteur', 'PA', 'Préservation du caractère résidentiel et de la qualité de vie', 'Opposé aux immeubles de grande hauteur qui peuvent nuire au caractère des quartiers', NULL),
('equipe_priorite_quebec', 'q8_interdire_essence_centre_ville', 'PA', 'Réserves sur les réglementations excessives', 'Opposé aux mesures environnementales trop contraignantes sans acceptabilité sociale', NULL),
('equipe_priorite_quebec', 'q9_protection_espaces_verts', 'FA', NULL, NULL, NULL),
('equipe_priorite_quebec', 'q10_transition_carboneutre', 'FA', NULL, NULL, NULL),
('equipe_priorite_quebec', 'q11_reduction_dechets', 'PD', NULL, NULL, NULL),
('equipe_priorite_quebec', 'q12_augmentation_taxes', 'FD', NULL, NULL, NULL),
('equipe_priorite_quebec', 'q13_pouvoir_conseils_quartier', 'PA', NULL, NULL, NULL),
('equipe_priorite_quebec', 'q14_reduction_dette', 'N', NULL, NULL, NULL),
('equipe_priorite_quebec', 'q15_avantages_fiscaux_entreprises', 'N', NULL, NULL, NULL),
('equipe_priorite_quebec', 'q16_limitation_touristes', 'N', NULL, NULL, NULL),
('equipe_priorite_quebec', 'q17_soutien_organismes_communautaires', 'PA', NULL, NULL, NULL),
('equipe_priorite_quebec', 'q18_augmentation_effectifs_policiers', 'N', NULL, NULL, NULL),
('equipe_priorite_quebec', 'q19_investissement_infrastructures_loisirs_sportives', 'PA', NULL, NULL, NULL),
('equipe_priorite_quebec', 'q20_protection_patrimoine', 'N', NULL, NULL, NULL),
('equipe_priorite_quebec', 'q21_enjeux_prioritaires', 'PA', NULL, NULL, NULL),

-- Leadership Québec - Équipe Sam Hamad (LQ)
('leadership_quebec', 'q1_tramway', 'PD', 'Données actualisées 2025', 'Plutôt opposé au projet de tramway', NULL),
('leadership_quebec', 'q2_pistes_cyclables', 'PD', 'Données actualisées 2025', 'Plutôt opposé à prioriser les pistes cyclables au détriment des voies automobiles', NULL),
('leadership_quebec', 'q3_troisieme_lien', 'N', 'Données actualisées 2025', 'Position neutre sur le troisième lien routier', NULL),
('leadership_quebec', 'q4_priorite_mobilite_active', 'PD', 'Données actualisées 2025', 'Plutôt opposé à la réduction des stationnements', NULL),
('leadership_quebec', 'q5_quotas_logements_abordables', 'N', 'Données actualisées 2025', 'Position neutre sur les quotas de logements abordables', NULL),
('leadership_quebec', 'q6_reduction_depenses_taxes', 'PA', 'Données actualisées 2025', 'Plutôt en faveur de réduire les dépenses et taxes', NULL),
('leadership_quebec', 'q7_immeubles_grande_hauteur', 'N', 'Données actualisées 2025', 'Position neutre sur les immeubles de grande hauteur', NULL),
('leadership_quebec', 'q8_interdire_essence_centre_ville', 'N', 'Données actualisées 2025', 'Position neutre sur l''interdiction des véhicules à essence', NULL),
('leadership_quebec', 'q9_protection_espaces_verts', 'PD', 'Données actualisées 2025', 'Plutôt opposé à protéger les espaces verts si cela nuit au développement', NULL),
('leadership_quebec', 'q10_transition_carboneutre', 'N', 'Données actualisées 2025', 'Position neutre sur la transition des bâtiments carboneutres', NULL),
('leadership_quebec', 'q11_reduction_dechets', 'N', 'Données actualisées 2025', 'Position neutre sur l''amélioration de la collecte des ordures', NULL),
('leadership_quebec', 'q12_augmentation_taxes', 'PD', 'Données actualisées 2025', 'Plutôt opposé aux projets écoresponsables si cela augmente les taxes', NULL),
('leadership_quebec', 'q13_pouvoir_conseils_quartier', 'N', 'Valorise l''écoute citoyenne', 'Sans appuyer les structures formelles de conseils de quartier', NULL),
('leadership_quebec', 'q14_reduction_dette', 'PA', 'Discours récurrent sur la rigueur budgétaire et la saine gestion', 'Tendance à prioriser la discipline financière et le contrôle de la dette', NULL),
('leadership_quebec', 'q15_avantages_fiscaux_entreprises', 'PA', 'Données actualisées 2025', 'Plutôt en faveur des avantages fiscaux pour attirer les entreprises', NULL),
('leadership_quebec', 'q16_limitation_touristes', 'N', 'Non abordé dans la plateforme', 'Pas de position claire sur la limitation du tourisme', NULL),
('leadership_quebec', 'q17_soutien_organismes_communautaires', 'N', 'Données actualisées 2025', 'Position neutre sur le financement des organismes communautaires', NULL),
('leadership_quebec', 'q18_augmentation_effectifs_policiers', 'N', 'Aucun engagement clair sur l''augmentation ou la réduction', 'Neutre sur les effectifs policiers', NULL),
('leadership_quebec', 'q19_investissement_infrastructures_loisirs_sportives', 'PD', 'Données actualisées 2025', 'Plutôt opposé à investir davantage dans les parcs et arénas', NULL),
('leadership_quebec', 'q20_protection_patrimoine', 'N', 'Non abordé dans la plateforme 2025', 'Pas de position claire sur la protection du patrimoine', NULL),
('leadership_quebec', 'q21_enjeux_prioritaires', 'PA', 'Mobilité (SRB), rigueur fiscale, relance économique', 'Priorités : implication citoyenne et développement économique', NULL),

-- Québec d'abord (QD)
('quebec_dabord', 'q1_tramway', 'PA', 'Données actualisées 2025', 'Fortement en faveur du tramway', NULL),
('quebec_dabord', 'q2_pistes_cyclables', 'PA', 'Données actualisées 2025', 'Plutôt en faveur des pistes cyclables', NULL),
('quebec_dabord', 'q3_troisieme_lien', 'PA', 'Données actualisées 2025', 'Plutôt en faveur du troisième lien routier', NULL),
('quebec_dabord', 'q4_priorite_mobilite_active', 'N', 'Données actualisées 2025', 'Plutôt opposé à la réduction des stationnements centre-ville', NULL),
('quebec_dabord', 'q5_quotas_logements_abordables', 'N', 'Données actualisées 2025', 'Position neutre sur les quotas de logements abordables', NULL),
('quebec_dabord', 'q6_reduction_depenses_taxes', 'N', 'Données actualisées 2025', 'Position neutre sur la réduction des dépenses selon la capacité de payer', NULL),
('quebec_dabord', 'q7_immeubles_grande_hauteur', 'PD', 'Données actualisées 2025', 'Plutôt opposé aux immeubles de grande hauteur', NULL),
('quebec_dabord', 'q8_interdire_essence_centre_ville', 'PA', 'Données actualisées 2025', 'Plutôt en faveur d''interdire les véhicules à essence au centre-ville en 2035', NULL),
('quebec_dabord', 'q9_protection_espaces_verts', 'N', 'Données actualisées 2025', 'Position neutre sur les espaces verts', NULL),
('quebec_dabord', 'q10_transition_carboneutre', 'PA', 'Données actualisées 2025', 'Plutôt opposé à la transition des bâtiments carboneutres', NULL),
('quebec_dabord', 'q11_reduction_dechets', 'N', 'Données actualisées 2025', 'Plutôt en faveur de la collecte des ordures au 3 semaines', NULL),
('quebec_dabord', 'q12_augmentation_taxes', 'N', 'Données actualisées 2025', 'Plutôt opposé aux projets écoresponsables', NULL),
('quebec_dabord', 'q13_pouvoir_conseils_quartier', 'PA', 'Données actualisées 2025', 'Plutôt en faveur de donner plus de pouvoir aux conseils de quartier', NULL),
('quebec_dabord', 'q14_reduction_dette', 'PA', 'Données actualisées 2025', 'Position neutre sur la réduction des dépenses selon la capacité de payer', NULL),
('quebec_dabord', 'q15_avantages_fiscaux_entreprises', 'N', 'Données actualisées 2025', 'Position neutre sur les réductions de taxes', NULL),
('quebec_dabord', 'q16_limitation_touristes', 'PD', 'Données actualisées 2025', 'Plutôt en faveur de limiter le tourisme', NULL),
('quebec_dabord', 'q17_soutien_organismes_communautaires', 'N', 'Données actualisées 2025', 'Position neutre sur le financement des organismes communautaires', NULL),
('quebec_dabord', 'q18_augmentation_effectifs_policiers', 'PD', 'Données actualisées 2025', 'Plutôt opposé à augmenter les effectifs policiers', NULL),
('quebec_dabord', 'q19_investissement_infrastructures_loisirs_sportives', 'N', 'Données actualisées 2025', 'Position neutre sur l''investissement dans les parcs, arénas et terrains de sport', NULL),
('quebec_dabord', 'q20_protection_patrimoine', 'N', 'Données actualisées 2025', 'Position neutre sur la protection du patrimoine', NULL),
('quebec_dabord', 'q21_enjeux_prioritaires', 'PA', 'Données actualisées 2025', 'Priorités du parti selon leur orientation centriste pragmatique', NULL),

-- Québec forte et fière (QFF)
('quebec_forte_et_fiere', 'q1_tramway', 'FA', 'Positions publiques du maire sortant', 'A défendu le projet de tramway comme essentiel pour la ville', NULL),
('quebec_forte_et_fiere', 'q2_pistes_cyclables', 'FA', 'Réalisations de l''administration actuelle', 'A augmenté significativement le réseau cyclable pendant son mandat', NULL),
('quebec_forte_et_fiere', 'q3_troisieme_lien', 'PD', 'Déclarations publiques nuancées', 'A exprimé des réserves tout en reconnaissant certains besoins', NULL),
('quebec_forte_et_fiere', 'q4_priorite_mobilite_active', 'PA', 'Administration Marchand favorable au transport collectif', 'Fortement en faveur de la réduction des stationnements pour encourager le transport collectif', NULL),
('quebec_forte_et_fiere', 'q5_quotas_logements_abordables', 'PA', 'Données actualisées 2025', 'Plutôt en faveur des quotas de logements abordables', NULL),
('quebec_forte_et_fiere', 'q6_reduction_depenses_taxes', 'PD', 'Centre-gauche progressiste privilégiant l''investissement public', 'Opposé à la réduction des dépenses, préfère investir dans les services et projets d''avenir', NULL),
('quebec_forte_et_fiere', 'q7_immeubles_grande_hauteur', 'FD', 'Données actualisées 2025', 'Fortement opposé aux immeubles de grande hauteur', NULL),
('quebec_forte_et_fiere', 'q8_interdire_essence_centre_ville', 'PA', 'Administration Marchand engagée dans la transition écologique', 'Plutôt en faveur de l''interdiction des véhicules à essence comme mesure environnementale', NULL),
('quebec_forte_et_fiere', 'q9_protection_espaces_verts', 'FA', 'Données actualisées 2025', 'Fortement en faveur des espaces verts', NULL),
('quebec_forte_et_fiere', 'q10_transition_carboneutre', 'FA', 'Données actualisées 2025', 'Plutôt en faveur de la transition des bâtiments carboneutres', NULL),
('quebec_forte_et_fiere', 'q11_reduction_dechets', 'FD', 'Données actualisées 2025', 'Plutôt opposé à la collecte des ordures au 3 semaines', NULL),
('quebec_forte_et_fiere', 'q12_augmentation_taxes', 'PA', 'Données actualisées 2025', 'Plutôt en faveur des projets écoresponsables', NULL),
('quebec_forte_et_fiere', 'q13_pouvoir_conseils_quartier', 'FD', 'Données actualisées 2025', 'Fortement opposé à donner plus de pouvoir aux conseils de quartier', NULL),
('quebec_forte_et_fiere', 'q14_reduction_dette', 'N', 'Données actualisées 2025', 'Position neutre sur la réduction des dépenses selon la capacité de payer', NULL),
('quebec_forte_et_fiere', 'q15_avantages_fiscaux_entreprises', 'FD', 'Données actualisées 2025', 'Fortement opposé à offrir plus de réductions de taxes', NULL),
('quebec_forte_et_fiere', 'q16_limitation_touristes', 'FD', 'Données actualisées 2025', 'Position neutre sur la limitation des touristes', NULL),
('quebec_forte_et_fiere', 'q17_soutien_organismes_communautaires', 'N', 'Données actualisées 2025', 'Position neutre sur le financement des organismes communautaires', NULL),
('quebec_forte_et_fiere', 'q18_augmentation_effectifs_policiers', 'PA', 'Données actualisées 2025', 'Plutôt en faveur d''augmenter les effectifs policiers', NULL),
('quebec_forte_et_fiere', 'q19_investissement_infrastructures_loisirs_sportives', 'PA', 'Données actualisées 2025', 'Plutôt en faveur d''investir dans les parcs, arénas et terrains de sport', NULL),
('quebec_forte_et_fiere', 'q20_protection_patrimoine', 'PA', 'Données actualisées 2025', 'Plutôt en faveur de la protection du patrimoine', NULL),
('quebec_forte_et_fiere', 'q21_enjeux_prioritaires', 'FA', 'Priorités du parti selon leur orientation centre-gauche progressiste', 'Priorités du parti: tramway, logement abordable, environnement', NULL),

-- Respect citoyens (RC)
('respect_citoyens', 'q1_tramway', 'FD', 'Données actualisées 2025', 'S''oppose aux grands projets jugés coûteux comme le tramway', NULL),
('respect_citoyens', 'q2_pistes_cyclables', 'FD', 'Données actualisées 2025', 'Fortement opposé à la priorisation des pistes cyclables au détriment des voies automobiles', NULL),
('respect_citoyens', 'q3_troisieme_lien', 'FA', 'Plateforme électorale Respect citoyens', 'Projet prioritaire du parti, perçu comme essentiel pour le développement régional', NULL),
('respect_citoyens', 'q4_priorite_mobilite_active', 'FD', 'Données actualisées 2025', 'Fortement opposé à la réduction des stationnements au profit du transport collectif', NULL),
('respect_citoyens', 'q5_quotas_logements_abordables', 'FD', 'Données actualisées 2025', 'Fortement opposé aux quotas obligatoires de logements abordables', NULL),
('respect_citoyens', 'q6_reduction_depenses_taxes', 'FA', 'Objectif majeur du parti : saine gestion et discipline budgétaire', 'Fortement en faveur de la réduction des dépenses et taxes municipales', NULL),
('respect_citoyens', 'q7_immeubles_grande_hauteur', 'FA', 'Données actualisées 2025', 'Fortement en faveur des immeubles de grande hauteur pour maximiser l''utilisation des terrains', NULL),
('respect_citoyens', 'q8_interdire_essence_centre_ville', 'FD', 'S''oppose aux plans jugés idéologiques et irréalistes de transition écologique', 'Fortement opposé aux mesures environnementales contraignantes comme l''interdiction des véhicules à essence', NULL),
('respect_citoyens', 'q9_protection_espaces_verts', 'FD', 'Données actualisées 2025', 'Fortement opposé aux espaces verts si cela nuit au développement immobilier', NULL),
('respect_citoyens', 'q10_transition_carboneutre', 'FD', 'Données actualisées 2025', 'Fortement opposé à la transition des bâtiments carboneutres si coûteuse', NULL),
('respect_citoyens', 'q11_reduction_dechets', 'FD', 'Plateforme électorale Respect citoyens', 'Peu de prise de position concrète ; thème secondaire dans leur plateforme', NULL),
('respect_citoyens', 'q12_augmentation_taxes', 'FD', 'Données actualisées 2025', 'Fortement opposé aux projets écoresponsables si cela augmente les taxes', NULL),
('respect_citoyens', 'q13_pouvoir_conseils_quartier', 'FA', 'Données actualisées 2025', 'Fortement en faveur de donner plus de pouvoir aux conseils de quartier', NULL),
('respect_citoyens', 'q14_reduction_dette', 'FA', 'Plateforme électorale Respect citoyens', 'Objectif majeur du parti : saine gestion et discipline budgétaire', NULL),
('respect_citoyens', 'q15_avantages_fiscaux_entreprises', 'FA', 'Plateforme électorale Respect citoyens', 'Pour stimuler l''économie locale et attirer les investisseurs', NULL),
('respect_citoyens', 'q16_limitation_touristes', 'PA', 'Données actualisées 2025', 'Plutôt en faveur de limiter le tourisme pour protéger la qualité de vie', NULL),
('respect_citoyens', 'q17_soutien_organismes_communautaires', 'PD', 'Données actualisées 2025', 'Plutôt opposé à augmenter le financement des organismes communautaires', NULL),
('respect_citoyens', 'q18_augmentation_effectifs_policiers', 'FA', 'Données actualisées 2025', 'Fortement en faveur d''augmenter les effectifs policiers', NULL),
('respect_citoyens', 'q19_investissement_infrastructures_loisirs_sportives', 'FA', 'Données actualisées 2025', 'Fortement en faveur d''investir dans les parcs, arénas et terrains de sport', NULL),
('respect_citoyens', 'q20_protection_patrimoine', 'FD', 'Données actualisées 2025', 'Fortement opposé au renforcement des règles de protection du patrimoine', NULL),
('respect_citoyens', 'q21_enjeux_prioritaires', 'FA', 'Plateforme électorale Respect citoyens', 'Le parti met de l''avant : troisième lien, fiscalité, développement économique et participation citoyenne', NULL),

-- Transition Québec (TQ)
('transition_quebec', 'q1_tramway', 'FA', 'Données actualisées 2025', 'Fortement en faveur du tramway', NULL),
('transition_quebec', 'q2_pistes_cyclables', 'FA', 'Données actualisées 2025', 'Fortement en faveur des pistes cyclables', NULL),
('transition_quebec', 'q3_troisieme_lien', 'FD', 'Données actualisées 2025', 'Fortement opposé au troisième lien routier', NULL),
('transition_quebec', 'q4_priorite_mobilite_active', 'FA', 'Données actualisées 2025', 'Fortement en faveur de la réduction des stationnements centre-ville', NULL),
('transition_quebec', 'q5_quotas_logements_abordables', 'FA', 'Données actualisées 2025', 'Fortement en faveur des quotas de logements abordables', NULL),
('transition_quebec', 'q6_reduction_depenses_taxes', 'FD', 'Données actualisées 2025', 'Fortement opposé à la réduction des dépenses selon la capacité de payer', NULL),
('transition_quebec', 'q7_immeubles_grande_hauteur', 'FD', 'Données actualisées 2025', 'Fortement opposé aux immeubles de grande hauteur - préfère densification réfléchie', NULL),
('transition_quebec', 'q8_interdire_essence_centre_ville', 'FA', 'Données actualisées 2025', 'Fortement en faveur d''interdire les véhicules à essence au centre-ville en 2035', NULL),
('transition_quebec', 'q9_protection_espaces_verts', 'FA', 'Données actualisées 2025', 'Fortement en faveur des espaces verts', NULL),
('transition_quebec', 'q10_transition_carboneutre', 'FA', 'Données actualisées 2025', 'Fortement en faveur de la transition des bâtiments carboneutres', NULL),
('transition_quebec', 'q11_reduction_dechets', 'FD', 'Données actualisées 2025', 'Fortement opposé à la collecte des ordures au 3 semaines', NULL),
('transition_quebec', 'q12_augmentation_taxes', 'FA', 'Données actualisées 2025', 'Fortement en faveur des projets écoresponsables', NULL),
('transition_quebec', 'q13_pouvoir_conseils_quartier', 'PD', 'Données actualisées 2025', 'Fortement en faveur de donner plus de pouvoir aux conseils de quartier', NULL),
('transition_quebec', 'q14_reduction_dette', 'FD', 'Données actualisées 2025', 'Plutôt opposé à réduire les dépenses selon la capacité de payer', NULL),
('transition_quebec', 'q15_avantages_fiscaux_entreprises', 'FD', 'Données actualisées 2025', 'Fortement opposé à offrir plus de réductions de taxes', NULL),
('transition_quebec', 'q16_limitation_touristes', 'N', 'Données actualisées 2025', 'Position neutre sur la limitation des touristes', NULL),
('transition_quebec', 'q17_soutien_organismes_communautaires', 'PA', 'Données actualisées 2025', 'Plutôt en faveur du financement des organismes communautaires', NULL),
('transition_quebec', 'q18_augmentation_effectifs_policiers', 'FD', 'Données actualisées 2025', 'Plutôt opposé à augmenter les effectifs policiers', NULL),
('transition_quebec', 'q19_investissement_infrastructures_loisirs_sportives', 'FD', 'Données actualisées 2025', 'Fortement en faveur d''investir dans les parcs, arénas et terrains de sport', NULL),
('transition_quebec', 'q20_protection_patrimoine', 'PA', 'Données actualisées 2025', 'Plutôt en faveur de la protection du patrimoine', NULL),
('transition_quebec', 'q21_enjeux_prioritaires', 'FA', 'Priorités du parti selon leur orientation écologiste progressiste', 'Priorités : logement abordable, environnement, transport durable', NULL);

-- Vérification de l'insertion
SELECT 
  'Positions insérées' as status,
  COUNT(*) as count,
  NOW() as timestamp
FROM party_positions;

-- Vérification par parti
SELECT 
  p.name,
  COUNT(pp.id) as positions_count
FROM parties p
LEFT JOIN party_positions pp ON p.id = pp.party_id
GROUP BY p.id, p.name
ORDER BY p.name;