-- ========================================================================
-- MIGRATION 2: INSÉRER LES QUESTIONS DE LA BOUSSOLE MUNICIPALE
-- ========================================================================
-- À exécuter dans Supabase SQL Editor APRÈS 01_create_tables.sql
-- Date: 2025-09-21
-- ========================================================================

-- ========================================================================
-- INSÉRER LES 21 QUESTIONS DE LA BOUSSOLE MUNICIPALE
-- ========================================================================

INSERT INTO questions (
  id, text, category, response_type, description, response_format,
  agreement_options, importance_options, importance_direct_options,
  priority_options, custom_agreement_labels, custom_importance_direct_labels,
  order_index, municipality_id, is_generic
) VALUES

-- Q1 - Tramway
('q1_tramway',
 'La municipalité devrait investir davantage dans le projet de tramway, même si cela implique une hausse des taxes municipales.',
 'Mobilité et transport',
 'agreement',
 NULL,
 'standard',
 '["FA", "PA", "N", "PD", "FD", "IDK"]',
 '[5, 4, 3, 2, 1]',
 NULL,
 NULL,
 NULL,
 NULL,
 0,
 'quebec',
 false),

-- Q2 - Pistes cyclables
('q2_pistes_cyclables',
 'La municipalité devrait développer davantage les pistes cyclables, même si cela réduit l''espace pour les voitures.',
 'Mobilité et transport',
 'agreement',
 'Cette question évalue la priorité accordée aux transports actifs versus l''automobile.',
 'standard',
 '["FA", "PA", "N", "PD", "FD", "IDK"]',
 '[5, 4, 3, 2, 1]',
 NULL,
 NULL,
 NULL,
 NULL,
 1,
 'quebec',
 true),

-- Q3 - Troisième lien
('q3_troisieme_lien',
 'La Ville de Québec devrait activement soutenir la réalisation d''un troisième lien routier entre Québec et Lévis.',
 'Mobilité et transport',
 'agreement',
 NULL,
 'standard',
 '["FA", "PA", "N", "PD", "FD", "IDK"]',
 '[5, 4, 3, 2, 1]',
 NULL,
 NULL,
 NULL,
 NULL,
 2,
 'quebec',
 false),

-- Q4 - Priorité mobilité active
('q4_priorite_mobilite_active',
 'Pour améliorer l''attractivité du centre-ville, la priorité devrait être donnée aux piétons, cyclistes et au transport collectif, même si cela implique de réduire l''espace dédié à l''automobile (stationnements, voies de circulation, etc.).',
 'Mobilité et transport',
 'agreement',
 NULL,
 'standard',
 '["FA", "PA", "N", "PD", "FD", "IDK"]',
 '[5, 4, 3, 2, 1]',
 NULL,
 NULL,
 NULL,
 NULL,
 3,
 'quebec',
 true),

-- Q5 - Quotas logements abordables
('q5_quotas_logements_abordables',
 'La municipalité devrait imposer des quotas de logements abordables dans tous les nouveaux projets de développement résidentiel.',
 'Logement et aménagement',
 'agreement',
 NULL,
 'standard',
 '["FA", "PA", "N", "PD", "FD", "IDK"]',
 '[5, 4, 3, 2, 1]',
 NULL,
 NULL,
 NULL,
 NULL,
 4,
 'quebec',
 true),

-- Q6 - Réduction dépenses et taxes
('q6_reduction_depenses_taxes',
 'Il est prioritaire de réduire les dépenses municipales pour éviter une hausse des taxes foncières.',
 'Finances municipales',
 'agreement',
 NULL,
 'standard',
 '["FA", "PA", "N", "PD", "FD", "IDK"]',
 '[5, 4, 3, 2, 1]',
 NULL,
 NULL,
 NULL,
 NULL,
 5,
 'quebec',
 true),

-- Q7 - Immeubles de grande hauteur
('q7_immeubles_grande_hauteur',
 'La municipalité devrait autoriser la construction d''immeubles de plus grande hauteur pour répondre aux besoins en logement, même dans les quartiers historiques.',
 'Logement et aménagement',
 'agreement',
 NULL,
 'standard',
 '["FA", "PA", "N", "PD", "FD", "IDK"]',
 '[5, 4, 3, 2, 1]',
 NULL,
 NULL,
 NULL,
 NULL,
 6,
 'quebec',
 true),

-- Q8 - Interdire essence centre-ville
('q8_interdire_essence_centre_ville',
 'La Ville devrait interdire l''accès des véhicules à essence dans certaines zones du centre-ville d''ici 2030.',
 'Environnement et énergie',
 'agreement',
 NULL,
 'standard',
 '["FA", "PA", "N", "PD", "FD", "IDK"]',
 '[5, 4, 3, 2, 1]',
 NULL,
 NULL,
 NULL,
 NULL,
 7,
 'quebec',
 true),

-- Q9 - Protection espaces verts
('q9_protection_espaces_verts',
 'Il est important de protéger les espaces verts et les milieux naturels, même si cela limite le développement urbain.',
 'Environnement et énergie',
 'agreement',
 NULL,
 'standard',
 '["FA", "PA", "N", "PD", "FD", "IDK"]',
 '[5, 4, 3, 2, 1]',
 NULL,
 NULL,
 NULL,
 NULL,
 8,
 'quebec',
 true),

-- Q10 - Transition carboneutre
('q10_transition_carboneutre',
 'La municipalité devrait exiger que tous les nouveaux bâtiments soient carboneutres d''ici 2030, même si cela augmente les coûts de construction.',
 'Environnement et énergie',
 'agreement',
 NULL,
 'standard',
 '["FA", "PA", "N", "PD", "FD", "IDK"]',
 '[5, 4, 3, 2, 1]',
 NULL,
 NULL,
 NULL,
 NULL,
 9,
 'quebec',
 true),

-- Q11 - Réduction déchets
('q11_reduction_dechets',
 'Améliorer la collecte des ordures et du recyclage devrait être une priorité, même si cela nécessite des investissements importants.',
 'Environnement et énergie',
 'agreement',
 NULL,
 'standard',
 '["FA", "PA", "N", "PD", "FD", "IDK"]',
 '[5, 4, 3, 2, 1]',
 NULL,
 NULL,
 NULL,
 NULL,
 10,
 'quebec',
 true),

-- Q12 - Augmentation taxes
('q12_augmentation_taxes',
 'La municipalité devrait augmenter les taxes foncières pour financer des projets écoresponsables, même si cela affecte le budget des citoyens.',
 'Environnement et énergie',
 'agreement',
 NULL,
 'standard',
 '["FA", "PA", "N", "PD", "FD", "IDK"]',
 '[5, 4, 3, 2, 1]',
 NULL,
 NULL,
 NULL,
 NULL,
 11,
 'quebec',
 true),

-- Q13 - Pouvoir conseils quartier
('q13_pouvoir_conseils_quartier',
 'Les conseils de quartier devraient avoir plus de pouvoir décisionnel sur les projets qui affectent leur secteur.',
 'Gouvernance et participation',
 'agreement',
 NULL,
 'standard',
 '["FA", "PA", "N", "PD", "FD", "IDK"]',
 '[5, 4, 3, 2, 1]',
 NULL,
 NULL,
 NULL,
 NULL,
 12,
 'quebec',
 true),

-- Q14 - Réduction dette
('q14_reduction_dette',
 'Réduire la dette municipale devrait être une priorité, même si cela nécessite de reporter certains projets.',
 'Finances municipales',
 'agreement',
 NULL,
 'standard',
 '["FA", "PA", "N", "PD", "FD", "IDK"]',
 '[5, 4, 3, 2, 1]',
 NULL,
 NULL,
 NULL,
 NULL,
 13,
 'quebec',
 true),

-- Q15 - Avantages fiscaux entreprises
('q15_avantages_fiscaux_entreprises',
 'La municipalité devrait offrir des avantages fiscaux aux entreprises pour les attirer, même si cela réduit les revenus municipaux à court terme.',
 'Développement économique',
 'agreement',
 NULL,
 'standard',
 '["FA", "PA", "N", "PD", "FD", "IDK"]',
 '[5, 4, 3, 2, 1]',
 NULL,
 NULL,
 NULL,
 NULL,
 14,
 'quebec',
 true),

-- Q16 - Limitation touristes
('q16_limitation_touristes',
 'La municipalité devrait limiter le nombre de touristes dans certains secteurs pour préserver la qualité de vie des résidents.',
 'Développement économique',
 'agreement',
 NULL,
 'standard',
 '["FA", "PA", "N", "PD", "FD", "IDK"]',
 '[5, 4, 3, 2, 1]',
 NULL,
 NULL,
 NULL,
 NULL,
 15,
 'quebec',
 true),

-- Q17 - Soutien organismes communautaires
('q17_soutien_organismes_communautaires',
 'La municipalité devrait augmenter le financement des organismes communautaires, même si cela nécessite une hausse des taxes.',
 'Services sociaux et communautaires',
 'agreement',
 NULL,
 'standard',
 '["FA", "PA", "N", "PD", "FD", "IDK"]',
 '[5, 4, 3, 2, 1]',
 NULL,
 NULL,
 NULL,
 NULL,
 16,
 'quebec',
 true),

-- Q18 - Augmentation effectifs policiers
('q18_augmentation_effectifs_policiers',
 'La municipalité devrait augmenter les effectifs policiers pour améliorer la sécurité, même si cela nécessite des investissements importants.',
 'Sécurité publique',
 'agreement',
 NULL,
 'standard',
 '["FA", "PA", "N", "PD", "FD", "IDK"]',
 '[5, 4, 3, 2, 1]',
 NULL,
 NULL,
 NULL,
 NULL,
 17,
 'quebec',
 true),

-- Q19 - Investissement infrastructures loisirs
('q19_investissement_infrastructures_loisirs_sportives',
 'Il est important d''investir davantage dans les parcs, arénas et installations sportives, même si cela augmente les dépenses municipales.',
 'Services sociaux et communautaires',
 'agreement',
 NULL,
 'standard',
 '["FA", "PA", "N", "PD", "FD", "IDK"]',
 '[5, 4, 3, 2, 1]',
 NULL,
 NULL,
 NULL,
 NULL,
 18,
 'quebec',
 true),

-- Q20 - Protection patrimoine
('q20_protection_patrimoine',
 'La protection du patrimoine architectural et historique devrait être une priorité, même si cela limite les possibilités de développement.',
 'Logement et aménagement',
 'agreement',
 NULL,
 'standard',
 '["FA", "PA", "N", "PD", "FD", "IDK"]',
 '[5, 4, 3, 2, 1]',
 NULL,
 NULL,
 NULL,
 NULL,
 19,
 'quebec',
 true),

-- Q21 - Priorités municipales (question de priorité)
('q21_priorites_municipales',
 'Classez par ordre d''importance les enjeux suivants pour votre municipalité',
 'Gouvernance et participation',
 'priority_ranking',
 NULL,
 'priority',
 NULL,
 NULL,
 NULL,
 '["Transport et mobilité", "Logement abordable", "Environnement et développement durable", "Sécurité publique", "Développement économique", "Services municipaux", "Finances municipales"]',
 NULL,
 NULL,
 20,
 'quebec',
 true)

ON CONFLICT (id) DO UPDATE SET
  text = EXCLUDED.text,
  category = EXCLUDED.category,
  response_type = EXCLUDED.response_type,
  description = EXCLUDED.description,
  response_format = EXCLUDED.response_format,
  agreement_options = EXCLUDED.agreement_options,
  importance_options = EXCLUDED.importance_options,
  importance_direct_options = EXCLUDED.importance_direct_options,
  priority_options = EXCLUDED.priority_options,
  custom_agreement_labels = EXCLUDED.custom_agreement_labels,
  custom_importance_direct_labels = EXCLUDED.custom_importance_direct_labels,
  order_index = EXCLUDED.order_index,
  municipality_id = EXCLUDED.municipality_id,
  is_generic = EXCLUDED.is_generic,
  updated_at = NOW();

-- Message de confirmation
DO $$
BEGIN
  RAISE NOTICE '✅ 21 questions insérées pour Québec';
  RAISE NOTICE '📋 Prochaine étape: Exécuter 03_insert_parties_data.sql';
END
$$;